scenario: |
  1. 처음 알게 된 계기 ex) 광고, 친구 추천, SKT 공식 홈페이지, 앱스토어
  2. 주로 사용하는 상황 ex) 업무 통화, 중요한 전화, 복잡한 내용의 통화
  3. 사용하는 이유 ex) 편의성, 자동 녹음, 텍스트 요약 기능
  4. 편리하게 느낀 순간 ex) 긴 통화 내용 요약, 중요 포인트 체크
  5. 돋보이는 점 ex) 정확성, 사용자 친화적, 빠른 변환 속도
  6. 불편한 부분 ex) 녹음 퀄리티, 앱 크래시, 저장 공간 문제
  7. 자동녹음의 어려움 여부 ex) 녹음 실패, 자동 저장 문제, 녹음 설정 복잡
  8. 텍스트 변환 오류 여부 ex)잘못된 내용 변환, 중요 정보 누락
  9. 개선 필요한 부분 ex) 더 정확한 변환, 더 빠른 변환 속도, 사용자 설정 기능
  10. 추가 희망 기능 ex) 다양한 언어 지원, 화자 구분 기능, 클라우드 저장
  11. 가장 크게 느낀 점 ex) 통화 관리의 편리성, 시간 절약
  12. 추가 의견 ex) 가격 관련 피드백, 고객 서비스 피드백, 추천할 의향

interview: |
  인터뷰어(I): 안녕하세요, 김수진 씨. 오늘 인터뷰에 참여해주셔서 감사합니다. 본 인터뷰는
  SKT 에이닷의 통화요약 기능에 대한 사용자 경험을 파악하기 위한 것입니다. 솔직한 의견을
  자유롭게 나눠주세요.
  김수진(S): 안녕하세요, 기꺼이 참여하겠습니다!
  I: SKT 에이닷의 통화요약 기능을 처음 알게 된 계기는 무엇인가요?
  S: 회사 동료가 사용하는 것을 보고 알게 되었어요.
  I: 그 동료는 어떻게 사용하던가요? 특별히 인상 깊었던 점이 있나요?
  S: 그 동료는 팀 미팅 후의 주요 논의 사항을 바로 텍스트로 확인하더라고요. 그게 너무 편리
  해 보여서요.
  I: 어떤 상황에서 주로 통화요약 기능을 사용하시나요?
  S: 업무 관련 중요한 통화나 클라이언트와의 의견 교환 시에 사용해요.
  I: 그런 상황에서 통화요약 기능이 없었다면 어떤 불편함을 느꼈을까요?
  S: 아마 중요한 부분을 놓치거나 기억하려고 계속 메모를 작성하느라 힘들었을 것 같아요.
  I: 통화요약 기능 사용 중 가장 편리하게 느꼈던 순간은 언제였나요?
  S: 클라이언트와의 중요한 의견 교환 후 바로 그 내용을 텍스트로 확인할 수 있었을 때요.
  I: 그 순간을 조금 더 자세히 설명해주실 수 있나요?
  S: 네, 중요한 프로젝트에 관한 논의가 있었는데, 통화 후 바로 요약된 내용을 보니 빠르게
  작업에 반영할 수 있어서요.
  I: 통화요약 기능을 사용하면서 불편하게 느낀 점이 있었다면, 구체적으로 어떤 부분이었나
  요?
  S: 가끔 변환된 텍스트에 오류가 있어서 원하는 정보를 찾는데 어려움이 있었어요.
  I: 그 오류는 어떠한 형태로 나타났나요? 예를 들어 설명해 주실 수 있을까요?
  S: 목소리의 높낮이나 강세에 따라 잘못 인식하는 경우가 있었어요. 예를 들면 "제안"을 "제
  간"이라고 인식하는 등의 문제가 있었습니다.
  I: 통화요약 기능을 더 자주 사용하게 만들기 위해서는 어떤 부분이 개선되어야 한다고 생각
  하시나요?
  S: 음성 인식의 정확도를 높이고, 녹음 실패 시 바로 알림을 받을 수 있게 해주면 좋겠어요.
  I: 그런 알림 기능이 있다면, 어떤 방식으로 알림을 받고 싶으신가요?
  S: 녹음이 제대로 이루어지지 않았을 때 바로 알림 메시지를 받을 수 있으면 좋겠어요.
  I: SKT 에이닷의 통화요약 기능을 사용하면서 가장 크게 느낀 점은 무엇인가요?
  S: 전반적으로 통화 내용을 빠르게 복습하고 기록하는 데 큰 도움이 되었어요.
  I: 그러한 도움을 받으면서 특히 더 효율적으로 업무를 처리할 수 있었다면, 구체적인 예시를
  들어 설명해주실 수 있나요?
  S: 예를 들면, 클라이언트와의 미팅 후 바로 통화 내용을 기반으로 회의록을 작성하거나, 필
  요한 자료를 준비할 수 있었어요.
  I: 김수진 씨, 소중한 의견을 공유해 주셔서 감사합니다. 인터뷰가 끝났습니다.
  S: 감사합니다. 좋은 서비스가 되길 바라요!
